`web-ext` can be installed with `brew`
mozilla/extension-workshop pull request #1759
Opened 2023-12-17 13:56 UTC by abitrolly

2023-12-18 07:39 UTC, rebloor requested changes
@abitrolly Thanks for spotting this omission

2023-12-18 07:39 UTC, rebloor commented on src/content/documentation/develop/getting-started-with-web-ext.md
> +`web-ext` is a node-based application than can be installed it with `brew` or natively with [nodejs/npm](https://nodejs.org/) tool.
```suggestion
`web-ext` is a node-based application. You install it with `brew` or the [nodejs](https://nodejs.org/) npm tool.
```

2023-12-18 07:39 UTC, rebloor commented on src/content/documentation/develop/getting-started-with-web-ext.md
> +Installing with `brew`:
```suggestion
Install with `brew` using:
```

2023-12-18 07:39 UTC, rebloor commented on src/content/documentation/develop/getting-started-with-web-ext.md
> +Installing with `npm`:
```suggestion
Install with `npm` using:
```

2023-12-18 11:13 UTC, abitrolly commented
Thanks for the suggestions. Applied.

2023-12-20 01:14 UTC, rebloor approved these changes

2023-12-20 01:15 UTC, merged