Allow enterprise extensions to use storage.managed to grant consent.
mozilla/extension-workshop pull request #1785
Opened 2024-01-29 15:23 UTC by mkaply

2024-02-02 10:37 UTC, dotproto approved these changes
I _think_ this is sufficient for an initial update but I would also like to have @wagnerand approve before merging. 

We should follow up this PR with more detailed guidance for developers. I've opened #1786 to track that work.

2024-02-06 10:55 UTC, wagnerand requested changes

2024-02-06 10:55 UTC, wagnerand commented on src/content/documentation/develop/best-practices-for-collecting-user-data-consents.md
> +Note: For extensions managed by enterprise policy, consent may be granted outside of the extension. Policy-managed extensions may use storage.managed to detect such a grant and skip the consent confi
How do we define "extensions managed by enterprise policy"?

2024-02-06 10:55 UTC, wagnerand commented on src/content/documentation/develop/best-practices-for-collecting-user-data-consents.md
> +Note: For extensions managed by enterprise policy, consent may be granted outside of the extension. Policy-managed extensions may use storage.managed to detect such a grant and skip the consent confi
> ...consent may be granted outside of the extension. Policy-managed extensions may use storage.managed to detect such a grant and skip the consent confirmation step.

Can we rephrase this to clarify what it means and what the requirements are? This is using `may` a lot, some things should probably use `must`. For example, is it clear that using `storage.management` is the **only** (approved) way to bypass the disclosure and consent experience?

2024-02-06 10:55 UTC, wagnerand commented on src/content/documentation/develop/best-practices-for-collecting-user-data-consents.md
> +Note: For extensions managed by enterprise policy, consent may be granted outside of the extension. Policy-managed extensions may use storage.managed to detect such a grant and skip the consent confi
> ... and skip the consent confirmation step.

Let's make it clear and add a note that the disclosure and consent experience still needs to be implemented in the add-on and shown when the respective `storage.managed` key is not set.

2024-02-06 14:26 UTC, mkaply commented
New patch pushed with updated text approved by Andreas.

2024-02-06 18:57 UTC, wagnerand approved these changes

2024-02-06 19:01 UTC, merged