[WIP] Duplicated links converted into references in markdown
mozilla/extension-workshop pull request #915
Opened 2021-02-17 09:07 UTC by Patil2099

Fixes #241

2021-02-18 09:10 UTC, Patil2099 commented
@muffinresearch Can you please review this pr ?

2021-02-18 10:49 UTC, championshuttler requested changes
Thanks @Patil2099 for the contribution, I think its better to list all the links at the end of the file instead putting them in between the text to keep the file clean and also a standard for markdown files i guess

2021-02-26 09:38 UTC, muffinresearch commented
@Patil2099 thanks for this PR I'm going to take a look at this today.

2021-02-26 20:44 UTC, muffinresearch requested changes
There's a few mistakes in here that are causing broken links that'll need fixing up.

## Improving the references

In addition, here's a few suggestions to improve on the references. 

A good reference needs to be descriptive. Ideally try and avoid using a reference that has a `-link` suffix. The reference should be reasonably clear.

There's a lot places where the linked text could be the reference. This will work if the text that's linked is descriptive (and works from the duplication perspective) you can use just that and no reference. (As mentioned in the [original bug ](https://github.com/mozilla/extension-workshop/issues/241) there's a few ways to do this see [the markdown cheatsheet ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)for the list)

```markdown
Or leave it empty and use the [link text itself].

[link text itself]: http://www.reddit.com
```
 
Which renders as:

Or leave it empty and use the [link text itself].

[link text itself]: http://www.reddit.com

## Testing

To check this I'm diffing the output of a production build from `yarn build:production` on master and from this branch (running the diff on each dist directory - copied each one to a different location to do this). If you can do the same you'll catch any differences that are more than just metadata related.

Overall there should be no changes to the links in the output if this worked correctly.

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/build-an-accessible-extension.md
> +The markup in the popup should follow [standard web accessibility guidelines].
This one is missing the same text as the others so it's not converted.

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/comparison-with-the-add-on-sdk.md
> +| Attach scripts to pages matching URL pattern | [`page-mod`][page-mod-link]API     | [`content-scripts`][content-script-link] key |
A space was erroneously deleted before the word "API"

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/comparison-with-xul-xpcom-extensions.md
> +| [`nsIClipboard`](https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIClipboard)
This is not right it's resulting in the link text of 'f'

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/differences-between-desktop-and-android-extensions.md
> +[page-action]:https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/pageAction/hide
This is the wrong link. It's the same as the one above.

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/request-the-right-permissions.md
> +Making a runtime permission request is straightforward. Include any permissions you want to request under the `manifest.json` `"[optional_permissions][optional-permission]"` key. Then pass the permis
This was broken before see: https://github.com/mozilla/extension-workshop/issues/926 but back ticks should be inside the square brackets. WIth backticks, the double quotes are redundant.

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/develop/test-permission-requests.md
> +[upadte-link]:https://developer.mozilla.org/docs/Mozilla/Add-ons/Updates
This is a typo resulting in a failed replacement.

2021-02-26 20:44 UTC, muffinresearch commented on src/content/documentation/publish/make-money-from-browser-extensions.md
> +[opencollective]:https://www.micropayment.de/
This is the wrong link for the ref.

2021-03-15 16:21 UTC, caitmuenster commented
Hey @Patil2099, are you still interested in this issue?

2021-03-18 05:30 UTC, Patil2099 commented
I will have a look at this on weekend. @caitmuenster

2021-04-19 10:01 UTC, Patil2099 commented
Sorry, I was busy with some work. I will open a new pr by tomorrow.

2021-04-19 10:02 UTC, closed without merging