WIP - update themes pages
mozilla/extension-workshop pull request #959
Opened 2021-04-01 23:26 UTC by caitmuenster

🚧 WIP 🚧 

Fixes #956. 

I'm breaking up some of the content from the Themes Concepts pages to make the content a little bit more digestible.

2021-04-13 18:00 UTC, muffinresearch requested changes
Needs the json updating because otherwise the nav doesn't work correctly.

2021-04-13 18:00 UTC, muffinresearch commented on src/data/pages.json
> +                     "url": "multiple-image-themes"
I think all of these `"url"` keys should be `"id"` instead.

2021-04-16 21:53 UTC, caitmuenster commented
Thanks @muffinresearch! Most recent commit should fix the json.

2021-04-20 20:10 UTC, muffinresearch approved these changes
r+

2021-04-21 15:44 UTC, merged